### ISSUE TITLE
Please create a tag for Rocq 9.0 in Rocq Platform 2025.09

### ISSUE THREAD

**Issue by Justme0606** [mit-plv/fiat-crypto#2146]
**Note: There was a compilation error with version 0.1.3 when i tried to build with Rocq 9.0**

The Rocq team released Rocq `9.0.0` on March 12th, 2025.
The corresponding Rocq Platform release `2025.09` should be released before **Oct 24th, 2025**.
It can be delayed in case of difficulties until Nov 21st, 2025, but this should be an exception.

This issue is to inform you that to our (possibly a few days old) best knowledge the latest released version of your project (0.1.3) **does not work** with Rocq `9.0.0`.
We tried to remove version restrictions in opam files and possibly make or configure files, but this did not suffice.

Please note that in Rocq Platform CI (unlike Rocq CI) we test only released / tagged versions. Rocq CI is currently testing commit 9e79fa6d3e8427c4f75321dbd426c86c483891c1
eedc9c86c55487cfcf7b40234e8780b8bd8b24db on repository https://github.com/mit-plv/fiat-crypto
https://github.com/mit-plv/fiat-crypto - which likely means that this commit does work in Rocq CI.

Could you please create a tag and opam package, or communicate us any existing tag that works with Rocq branch v9.0, **preferably before Sep 26th, 2025**?
In case we might have to delay the Rocq Platform release cause of issues with your project, we would prefer to be informed about the situation as early as possible.

In case the tag and opam package are available before Aug 28th, 2025, it will be included in an early Rocq Platform beta release of the for Rocq 9.0.0.

The working branch of Rocq Platform, can be found here [main](https://github.com/rocq-prover/platform/tree/main).
It contains package pick [`~9.0+preview~2025.08`](https://github.com/rocq-prover/platform/tree/main/package_picks/package-pick-9.0+preview~2025.08.sh) which already supports Rocq version `9.0.0` and contains already working (possibly patched / commit pinned) Rocq Platform packages.

Please **don't** close this issue, even after creating the new tag and/or opam package.
We will close the issue after updating Rocq Platform.
This is a measure of 'double book keeping' in order to avoid that we ship the wrong version.

In any case, Rocq Platform won't be released before this issue is closed!

Thanks!

P.S.: this issue has been created automatically based on CI status.

CC: https://github.com/rocq-prover/platform/issues/481

**Comment by andres-erbsen** [comment]
I will try to get to this, but I have a bunch of other important stuff on my plate, and it may or may not happen.

Seeing that the coq-platform status was discussed on a Coq call, I would like to add that creating releases for platform inclusion is an unpleasant chore with zero additional benefits from my perspective. If it was up to me, I would like Coq platform to ship fiat-crypto HEAD, and the versions of dependencies pinned there. (I believe that your processes make sense in the context of other projects, and I appreciate all the effort you put into distributing these libraries; the nuisance here is from an unlucky combination between the coq-platform process and fiat-crypto being a tightly coupled multirepo).
